Document: puppet-code
Title: Debian puppet-code Manual
Author: <insert document author here>
Abstract: This manual describes what puppet-code is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/puppet-code/puppet-code.sgml.gz

Format: postscript
Files: /usr/share/doc/puppet-code/puppet-code.ps.gz

Format: text
Files: /usr/share/doc/puppet-code/puppet-code.text.gz

Format: HTML
Index: /usr/share/doc/puppet-code/html/index.html
Files: /usr/share/doc/puppet-code/html/*.html
