#!/usr/bin/env bash
set -eux

for module in modules/profile modules/role environments/development/modules/profile
do
  puppet-lint --fail-on-warnings $module
done

make bumpversion
git add debian/changelog
